"""Initial migration with all models

Revision ID: 2778fd77b13f
Revises:
Create Date: 2025-10-19 13:38:14.180121

"""
from alembic import op
import sqlalchemy as sa
from flask_security.datastore import AsaList


# revision identifiers, used by Alembic.
revision = '2778fd77b13f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', AsaList(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('current_login_ip', sa.String(length=64), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('tf_primary_method', sa.String(length=64), nullable=True),
    sa.Column('tf_totp_secret', sa.String(length=255), nullable=True),
    sa.Column('tf_phone_number', sa.String(length=128), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('enumerator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('upload_status', sa.String(length=50), nullable=True),
    sa.CheckConstraint("session_type IN ('child', 'parent')", name='check_session_type'),
    sa.ForeignKeyConstraint(['enumerator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index('idx_enumerator_id', ['enumerator_id'], unique=False)

    op.create_table('child_session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.String(length=255), nullable=False),
    sa.Column('child_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('survey_status', sa.String(length=50), nullable=True),
    sa.Column('survey_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_session', schema=None) as batch_op:
        batch_op.create_index('idx_child_family', ['family_id'], unique=False)

    op.create_table('parent_session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.String(length=255), nullable=False),
    sa.Column('child1_name', sa.String(length=255), nullable=False),
    sa.Column('child2_name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.Column('survey_status', sa.String(length=50), nullable=True),
    sa.Column('survey_completed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_survey_status', sa.String(length=50), nullable=True),
    sa.Column('exit_survey_completed_at', sa.DateTime(), nullable=True),
    sa.Column('slider_status', sa.String(length=50), nullable=True),
    sa.Column('slider_started_at', sa.DateTime(), nullable=True),
    sa.Column('slider_completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("group_type IN ('treatment', 'control')", name='check_group_type'),
    sa.ForeignKeyConstraint(['id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_session', schema=None) as batch_op:
        batch_op.create_index('idx_parent_family', ['family_id'], unique=False)

    op.create_table('survey_response',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'survey_id', 'question_id', name='unique_session_survey_question')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_index('idx_session_survey', ['session_id', 'survey_id'], unique=False)

    op.create_table('slider_response',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('parent_session_id', sa.String(length=255), nullable=False),
    sa.Column('scenarios_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_number', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('child1_investment', sa.Integer(), nullable=False),
    sa.Column('child2_investment', sa.Integer(), nullable=False),
    sa.Column('allocatable_budget', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('scenario_gamma', sa.Float(), nullable=False),
    sa.Column('scenario_sigma', sa.Float(), nullable=False),
    sa.Column('scenario_theta', sa.Float(), nullable=False),
    sa.Column('pre_earnings1', sa.Float(), nullable=False),
    sa.Column('pre_earnings2', sa.Float(), nullable=False),
    sa.Column('high_child', sa.Integer(), nullable=False),
    sa.Column('scenario_alpha', sa.Float(), nullable=False),
    sa.Column('child1_final_earnings', sa.Float(), nullable=False),
    sa.Column('child2_final_earnings', sa.Float(), nullable=False),
    sa.Column('aggregate_final_earnings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_session_id'], ['parent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slider_response', schema=None) as batch_op:
        batch_op.create_index('idx_parent_session_display_order', ['parent_session_id', 'display_order'], unique=False)
        batch_op.create_index('idx_scenarios_id', ['scenarios_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slider_response', schema=None) as batch_op:
        batch_op.drop_index('idx_scenarios_id')
        batch_op.drop_index('idx_parent_session_display_order')

    op.drop_table('slider_response')
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_index('idx_session_survey')

    op.drop_table('survey_response')
    with op.batch_alter_table('parent_session', schema=None) as batch_op:
        batch_op.drop_index('idx_parent_family')

    op.drop_table('parent_session')
    with op.batch_alter_table('child_session', schema=None) as batch_op:
        batch_op.drop_index('idx_child_family')

    op.drop_table('child_session')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index('idx_enumerator_id')

    op.drop_table('session')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
